export const environment = {
    production: true,
    apiMainUrl: "https://appsterdb.ackermann.digital",
    importPath: "api/import",
    itemsPath: "api/items",
    reviewedItemsPath: "api/items/reviewed",
    createdItemsPath: "api/items/created",
    reviewItemsPath: "api/items/review",
    topicsPath: "api/topics",
    typesPath: "api/types",
    loginPath: "login",
    logoutPath: "login",
    registerPath: "account",
    deregisterPath: "account",
    requestPasswordPath: "account",
    userPath: "api/user",
    languagesPath: "api/language",
    feedbackItemsPath: "api/feedback/item",
    deleteFeedbackPath: "api/feedback"
};